// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYGS9vkxAfTK7qcmcOW8pjUG4fA0eUeVA',
    appId: '1:305348507864:web:ebf7ff8e3e9da69834ffad',
    messagingSenderId: '305348507864',
    projectId: 'geo-fence-seb',
    authDomain: 'geo-fence-seb.firebaseapp.com',
    storageBucket: 'geo-fence-seb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiM7rLWJCPF0G4SZcNJL4CljR3gAJE0F0',
    appId: '1:305348507864:android:e2f47ab80dc6eb3634ffad',
    messagingSenderId: '305348507864',
    projectId: 'geo-fence-seb',
    storageBucket: 'geo-fence-seb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1UYf8avHQovxmgWj9fqnasksZmfDErng',
    appId: '1:305348507864:ios:2016e349b6e33bfa34ffad',
    messagingSenderId: '305348507864',
    projectId: 'geo-fence-seb',
    storageBucket: 'geo-fence-seb.appspot.com',
    iosClientId: '305348507864-g49jnh6k7c535j191m1orqoem3t5r41v.apps.googleusercontent.com',
    iosBundleId: 'com.example.geofence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1UYf8avHQovxmgWj9fqnasksZmfDErng',
    appId: '1:305348507864:ios:27849010c7870b4a34ffad',
    messagingSenderId: '305348507864',
    projectId: 'geo-fence-seb',
    storageBucket: 'geo-fence-seb.appspot.com',
    iosClientId: '305348507864-bgj78lpqe4709rgkgk9uk2k8lfu30dep.apps.googleusercontent.com',
    iosBundleId: 'com.example.geofence.RunnerTests',
  );
}
