// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh-3W_ebeofi9Idamx04PRMa_eG5OWyKU',
    appId: '1:207030088666:web:1c360209441121d6d6c6e3',
    messagingSenderId: '207030088666',
    projectId: 'geofencing-seb',
    authDomain: 'geofencing-seb.firebaseapp.com',
    storageBucket: 'geofencing-seb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6phfQFa6M7sJMuUW-t1GCeIPDP_dfqWo',
    appId: '1:207030088666:android:855ae27f44502202d6c6e3',
    messagingSenderId: '207030088666',
    projectId: 'geofencing-seb',
    storageBucket: 'geofencing-seb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6E6v_F1JTDnBaAK_abC5qC_ukCZtKwTg',
    appId: '1:207030088666:ios:6508895729f03c47d6c6e3',
    messagingSenderId: '207030088666',
    projectId: 'geofencing-seb',
    storageBucket: 'geofencing-seb.appspot.com',
    iosClientId: '207030088666-i5sf12uhh6tl730ga713dqm44lrjuorf.apps.googleusercontent.com',
    iosBundleId: 'com.example.geofence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6E6v_F1JTDnBaAK_abC5qC_ukCZtKwTg',
    appId: '1:207030088666:ios:2c237c91aafc9962d6c6e3',
    messagingSenderId: '207030088666',
    projectId: 'geofencing-seb',
    storageBucket: 'geofencing-seb.appspot.com',
    iosClientId: '207030088666-ab3g6s0a6lpefuq8bfjdjtamf9521ckv.apps.googleusercontent.com',
    iosBundleId: 'com.example.geofence.RunnerTests',
  );
}
